
server:
  port: 8081
spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/myshop
    username: root
    password: ocs6919da!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  thymeleaf:
    cache: false